Importing libraries

In [1]:
import pandas as pd

Reading enrichment dataset

In [2]:
f1 = pd.read_csv("../../../../data/stage_1/political_leaning_fips.csv")
f1['county'] = f1['county'].str.lower()
f1['county'] = f1['county'].str.strip()
f1

     state             county  countyfips  total_votes party_won  num_votes
0       DE        kent county       10001        87025       DEM      44552
1       DE  new castle county       10003       287633       DEM     195034
2       DE      sussex county       10005       129352       REP      71230
3       FL     alachua county       12001       142604       DEM      89704
4       FL       baker county       12003        14059       REP      11911
...    ...                ...         ...          ...       ...        ...
2986    AZ      graham county        4009        14996       REP       1052
2987    AZ    greenlee county        4011         3688       REP       2433
2988    AZ      la paz county        4012         7460       REP       5129
2989    AZ    maricopa county        4013      2068144       DEM    1040774
2990    AZ      mohave county        4015       104705       REP      78535

[2991 rows x 6 columns]

Reading merged COVID-19 super dataset and making necessary changes to column names before merging

In [3]:
f2 = pd.read_csv("../../../../data/stage_1/superdataset.csv")
f2.rename(columns = {'County_Name':'county'}, inplace = True)
f2.rename(columns = {'State':'state'}, inplace = True)
f2.rename(columns = {'countyFIPS':'countyfips'}, inplace = True)
f2

,countyfips,county,state,Date,Confirmed,Deaths,population
0,0,statewide unallocated,AL,2020-01-22,0,0,0
1,0,statewide unallocated,AL,2020-01-23,0,0,0
2,0,statewide unallocated,AL,2020-01-24,0,0,0
3,0,statewide unallocated,AL,2020-01-25,0,0,0
4,0,statewide unallocated,AL,2020-01-26,0,0,0
...,...,...,...,...,...,...,...
2346471,56045,weston county,WY,2022-02-03,1491,17,6927
2346472,56045,weston county,WY,2022-02-04,1496,17,6927
2346473,56045,weston county,WY,2022-02-05,1496,17,6927
2346474,56045,weston county,WY,2022-02-06,1496,17,6927
2346475,56045,weston county,WY,2022-02-07,1508,17,6927

Merging the two dataframes to obtain the merged superdataset with COVID-19 data and presdiential election data. Data is merged using the 'countyfips' and 'state' columns.

In [4]:
m1 = pd.merge(f2,f1,on=['countyfips','state'],how="inner")
m1

,countyfips,county_x,state,Date,Confirmed,Deaths,population,county_y,total_votes,party_won,num_votes
0,1001,autauga county,AL,2020-01-22,0,0,55869,autauga county,27770,REP,19838
1,1001,autauga county,AL,2020-01-23,0,0,55869,autauga county,27770,REP,19838
2,1001,autauga county,AL,2020-01-24,0,0,55869,autauga county,27770,REP,19838
3,1001,autauga county,AL,2020-01-25,0,0,55869,autauga county,27770,REP,19838
4,1001,autauga county,AL,2020-01-26,0,0,55869,autauga county,27770,REP,19838
...,...,...,...,...,...,...,...,...,...,...,...
2231279,56045,weston county,WY,2022-02-03,1491,17,6927,weston county,3542,REP,3107
2231280,56045,weston county,WY,2022-02-04,1496,17,6927,weston county,3542,REP,3107
2231281,56045,weston county,WY,2022-02-05,1496,17,6927,weston county,3542,REP,3107
2231282,56045,weston county,WY,2022-02-06,1496,17,6927,weston county,3542,REP,3107
2231283,56045,weston county,WY,2022-02-07,1508,17,6927,weston county,3542,REP,3107

Saving merged file to a csv file

In [5]:
m1.to_csv('../../../../data/stage_1/superdataset_political.csv',index=False)